# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: metrics_codechanged
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: willmayrink
          filename: img/metrics/metrics-codechanged.svg
          base: repositories, history
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_lines: yes
          plugin_lines_repository_limit: 2
          
          #repositories_skipped: +lowlighter/metrics
          
