# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: willmayrink
          template: classic
          base_hireable: true
          base: header, metadata
          config_timezone: America/Sao_Paulo
          #plugin_leetcode_user: willmayrink
          #plugin_leetcode_sections: solved, skills
          #plugin_achievements: yes
          #plugin_achievements_display: compact
          #plugin_achievements_secrets: yes
          filename: img/metrics/github-metrics.svg
          plugin_languages: true
          plugin_languages_ignored: ruby, coffeescript
          plugin_topics: yes
          plugin_topics_mode: icons
         
          
          
          
          
          
